### ISSUE TITLE
Ability to specify order for configs and environments

### ISSUE THREAD

**Issue by opendba** [configcat/terraform-provider-configcat#25]
### Is your feature request related to a problem? Please describe.

Currently it's not possible to define an order for configcat_config and configcat_enenvironment. They are linked with the product, but sometimes they end up in random order and require manual re-ordering in configcat console.

### Describe the solution you'd like

Provide order attribute to the configcat_config & configcat_environment resources.

**Comment by laliconfigcat** [comment]
Hello @opendba ,

Thanks for reaching out. Our Public Management API currently does not support ordering the resources and the Terraform provider uses our Public Management API. 
We just received another request regarding supporting the ordering in our Public Management API in the past few days from a customer. We added both of these to our backlog and we'll inform you if we made any progress with it.

By the way, if the order is not provided somehow for the resource we have a fallback to alphabetical ordering, and maybe that's why you see it as random. As a short-term workaround I can suggest you to prepend a number order before your resource names. I totally understand that it is not ideal, but it can work till we develop these features.

Cheers,

**Comment by laliconfigcat** [comment]
Hello @opendba ,

I just release v3.0.0 with supporting the order in the `configcat_product`, `configcat_config`, `configcat_environment` and the `configcat_setting` resources. It is a breaking change, you'll have to define order for these resources.
I hope you'll like it. 

If you are happy with our service, please help us grow by leaving a review. https://www.trustradius.com/welcome/configcat
It really makes a difference for us.

**Comment by laliconfigcat** [comment]
Hello @opendba ,

I'm closing this issue. Let us know if you have any questions. Have a nice day and happy feature flagging!

If you are happy with our service, please help us grow by leaving a review. https://www.trustradius.com/welcome/configcat
It really makes a difference for us.
